import Head from "next/head";
import HeroSection from "@/components/home/HeroSection";
import Showcase from "@/components/home/Showcase";
const posts = [
  {
    id: 1,
    date: "2022-08-02T10:15:00-07:00",
    category: {
      id: 1,
      slug: "/author/jane-smith",
      name: "Jane Smith",
      image: "#",
    },
    image: "https://source.unsplash.com/random/800x600",
    html: "",
    title: "10 Delicious and Healthy Smoothie Recipes",
    slug: "/blog/healthy-smoothie-recipes",
    description:
      "Smoothies are a great way to pack in the nutrients and enjoy a delicious meal or snack on the go. In this post, we’ll share 10 of our favorite smoothie recipes that are both healthy and tasty, from green smoothies to fruity blends.",
    author: {
      id: 1,
      slug: "/author/jane-smith",
      name: "Jane Smith",
      image: "#",
    },
  },
  {
    id: 2,
    date: "2022-08-02T10:15:00-07:00",
    category: {
      id: 1,
      slug: "/author/jane-smith",
      name: "Jane Smith",
      image: "#",
    },
    image: "https://source.unsplash.com/random/800x600",
    html: "",
    title: "10 Delicious and Healthy Smoothie Recipes",
    slug: "/blog/healthy-smoothie-recipes",
    description:
      "Smoothies are a great way to pack in the nutrients and enjoy a delicious meal or snack on the go. In this post, we’ll share 10 of our favorite smoothie recipes that are both healthy and tasty, from green smoothies to fruity blends.",
    author: {
      id: 1,
      slug: "/author/jane-smith",
      name: "Jane Smith",
      image: "#",
    },
  },
  {
    id: 3,
    date: "2022-08-02T10:15:00-07:00",
    category: {
      id: 1,
      slug: "/author/jane-smith",
      name: "Jane Smith",
      image: "#",
    },
    image: "https://source.unsplash.com/random/800x600",
    html: "",
    title: "10 Delicious and Healthy Smoothie Recipes",
    slug: "/blog/healthy-smoothie-recipes",
    description:
      "Smoothies are a great way to pack in the nutrients and enjoy a delicious meal or snack on the go. In this post, we’ll share 10 of our favorite smoothie recipes that are both healthy and tasty, from green smoothies to fruity blends.",
    author: {
      id: 1,
      slug: "/author/jane-smith",
      name: "Jane Smith",
      image: "#",
    },
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Beren Boden - Full Stack Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HeroSection />
        <Showcase posts={posts} />
      </main>
    </>
  );
}
